[[redirects]]
  from = "/sa/*"
  to = "https://simpleanalytics.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/scripts/*"
  to = "https://scripts.simpleanalyticscdn.com/:splat"
  status = 200
  force = true